database:
  engine: <connection string>
  tablenames:
    file:
      schema: null
      table: <file table>
    event:
      schema: null
      table: <event table>
  echo: false
  pool_class: QueuePool
ingester:
  storage: <storage area>
  plugin:
    name: Gen2Ingester
    config:

      # Settings specific to accessing the dataset repository.
      butler:
        root: <dataset repository>

      # Settings specific to ingesting raw images to the repository.
      ingest:
        task: lsst.pipe.tasks.ingest.IngestTask
        dryrun: false
        mode: link
        create: false
        ignoreIngested: false

  include_list: null
  exclude_list: null
  file_status: UNTRIED
  batch_size: 10
  daemon: true
  num_threads: 1
  pause: 1
logging:
  file: null
  format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  level: INFO
