database:
  engine: "postgres://tester:password@localhost:5432/test"
  tablenames:
    file:
      schema: null
      table: loc_inst_files
    event:
      schema: null
      table: loc_inst_gen2_file_events
  echo: false
  pool_class: QueuePool
ingester:
  storage: /data/storage
  plugin:
    name: Gen3Ingest
    config:
      root: /data/gen3repo
      config: null
      config_file: null
      ingest_task: lsst.obs.base.RawIngestTask
      output_run: null
      processes: 1
      transfer: symlink
  file_status: UNTRIED
  batch_size: 10
  daemon: true
  num_threads: 1
  pause: 1
logging:
  file: null
  format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  level: INFO
