database:
  engine: <connection string>
  tablenames:
    file:
      schema: null
      table: <file table>
    event:
      schema: null
      table: <event table>
  echo: false
  pool_class: QueuePool
ingester:
  storage: <storage area>
  plugin:
    name: Gen3Ingest
    config:

      # Settings specific to accessing the dataset repository.
      butler:
        root: <dataset repository>
        collection: null

      # Settings specific to ingesting raw images.
      ingest:
        config: null
        config_file: null
        processes: 1
        task: lsst.obs.base.RawIngestTask
        transfer: symlink

      # Settings specific to defining visits.
      visit:
        instrument: <instrument>
        config_file: null
        processes: 1
        task: lsst.obs.base.DefineVisitTask

  include_list: null
  exclude_list: null
  file_status: UNTRIED
  batch_size: 10
  daemon: true
  num_threads: 1
  pause: 1
logging:
  file: null
  format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  level: INFO
