database:
  engine: <connection string>
  tablenames:
    file:
      schema: null
      table: <file table>
    event:
      schema: null
      table: <event table>
  echo: false
  pool_class: QueuePool
ingester:
  storage: <storage area>
  plugin:
    name: Gen3Ingest

    # This section contains settings which are passed directly to the
    # LSST function responsible for creating the actual ingest task.
    config:

      # Gen3Ingest specific options.
      #
      # Note
      # ----
      # Only 'root' is required, others are optional.
      root: <dataset repository>
      config: null
      config_file: null
      ingest_task: lsst.obs.base.RawIngestTask
      output_run: null
      processes: 1
      transfer: symlink
      failFast: true

  include_list: null
  exclude_list: null
  file_status: UNTRIED
  batch_size: 10
  daemon: true
  num_threads: 1
  pause: 1
logging:
  file: null
  format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  level: INFO
